language: go

go:
  - 1.13


install:
  - make go-mod-cache

script:
  - make build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true