package mpeg21

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/bitsongofficial/go-bitsong/x/mpeg21/keeper"
	"github.com/bitsongofficial/go-bitsong/x/mpeg21/types"
)

const (
	ModuleName   = types.ModuleName
	StoreKey     = types.StoreKey
	RouterKey    = types.RouterKey
	QuerierRoute = types.QuerierRoute
)

var (
	// functions aliases
	NewQuerier          = keeper.NewQuerier
	NewKeeper           = keeper.NewKeeper
	NewHandler          = keeper.NewHandler
	DefaultGenesisState = types.DefaultGenesisState
	ValidateGenesis     = types.ValidateGenesis
	RegisterCodec       = types.RegisterCodec

	// variable aliases
	ModuleCdc = types.ModuleCdc
)

type (
	Keeper               = keeper.Keeper
	QueryContractParams  = types.QueryContractParams
	QueryContractsParams = types.QueryContractsParams
	Party                = types.Party
	GenesisState         = types.GenesisState
	MsgMpeg21StoreMCO    = types.MsgMpeg21StoreMCO
	Contract             = types.Contract
)
