package peer

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/bitsongofficial/go-bitsong/x/peer/keeper"
	"github.com/bitsongofficial/go-bitsong/x/peer/types"
)

const (
	ModuleName         = types.ModuleName
	StoreKey           = types.StoreKey
	RouterKey          = types.RouterKey
	QuerierRoute       = types.QuerierRoute
	EventTypeDataAdded = types.EventTypeDataAdded
	AttributeKeyCid    = types.AttributeKeyCid
	TypeMsgPut         = types.TypeMsgPut
)

var (
	// functions aliases
	GetBlockKey         = types.GetBlockKey
	NewGenesisState     = types.NewGenesisState
	DefaultGenesisState = types.DefaultGenesisState
	ValidateGenesis     = types.ValidateGenesis
	RegisterCodec       = types.RegisterCodec
	NewMsgPut           = types.NewMsgPut
	NewHandler          = keeper.NewHandler
	NewKeeper           = keeper.NewKeeper

	// variable aliases
	BlockKeyPrefix = types.BlockKeyPrefix
	ModuleCdc      = types.ModuleCdc
)

type (
	Keeper       = keeper.Keeper
	GenesisState = types.GenesisState
	MsgPut       = types.MsgPut
)
