name: Publish Docker image
#on:
#  release:
#    types: [published]
on: [push]

jobs:
  push_to_registry:
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-name: "linux"
#          - os: macos-latest
#            os-name: "osx"
#          - os: windows-latest
#            os-name: "windows"
    runs-on: ${{ matrix.os }}
    steps:
      # Check out code

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/go-bitsong:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}